Add controllers
dmt-100/java-shareit pull request #1
Opened 2023-10-06 18:01 UTC by dmt-100

2023-10-07 11:47 UTC, Fleaman777 requested changes

2023-10-07 11:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<List<ItemDto>> getAllItemsByUser(@RequestHeader("X-Sharer-User-Id") Long userId) {
X-Sharer-User-Id - можно было бы вынести в константу

2023-10-07 11:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +
поля должны быть private

2023-10-07 11:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +                .findFirst();
хороший стрим

2023-10-07 11:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +                new ItemNotFoundException("Вещь с id = " + itemId + "не найдена."));
и здесь тоже можно применить String.format

аналогично в др местах

2023-10-07 11:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +    public static long itemId = 0;  // сквозной счетчик вещей
а есть ли смысл делать эту переменную static ?

2023-10-07 11:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +    public static long userId = 0;
аналагичо, private

2023-10-08 05:06 UTC, dmt-100 commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +    public static long userId = 0;
Done!

2023-10-08 05:07 UTC, dmt-100 commented
Done!

2023-10-09 07:47 UTC, Fleaman777 approved these changes

2023-10-09 16:14 UTC, merged